# hkoca_cellbender: torch 2.1.2+cu121 (A100 + H100), cellbender 0.3.2, dill
name: hkoca_cellbender
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - libstdcxx-ng
  - pip:
      - --extra-index-url=https://download.pytorch.org/whl/cu121
      - "numpy<2"
      - torch==2.1.2
      - dill
      - cellbender==0.3.2
