name: hkoca_qc_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # R base
  - r-base>=4.2
  
  # System dependencies for plotting (fonts, text shaping, graphics)
  - cairo
  - harfbuzz
  - fribidi
  - pkg-config
  
  # CRAN Packages
  - r-seurat
  - r-mass
  - r-ggplot2
  - r-patchwork
  - r-cowplot
  - r-scales
  - r-reshape2
  - r-ggridges
  - r-ggrastr
  - r-ggrepel
  - r-yaml
  - r-dplyr
  
  # Bioconductor Packages
  - bioconductor-singlecellexperiment
  - bioconductor-scdblfinder
