# Kidney organoid cell types and markers v4
Nephron:
  marker_genes: [NPHS1, NPHS2, EPCAM, CLDN1, EYA1, PAX2, CUBN, CALB1] 
  subtypes:
    Nephron_progenitor_cells:
      marker_genes: [SIX1, SIX2, EYA1, PAX2, CITED1, PAX8, LYPD1]
    Podocytes:
      marker_genes: [NPHS1, NPHS2, MAFB, PODXL, TCF21, WT1, DDN, NTNG1, SYNPO, PTPRO, CLIC5, VEGFA] 
      subtypes:
        Precursor_podocytes:
          marker_genes: [OLFM3, MAFB, CCN2, NPHS1] 
        Mature_podocytes:
          marker_genes: [PTPRO, CLIC5, DDN, NPHS2, PODXL, NPHS1]
    Proximal_tubule:
      marker_genes: [CUBN, CDH6, LRP2, UGT2B7]
      subtypes:
        PT (PEC-like):
          marker_genes: [CLDN1, KCNJ16, CFAP43, ARMC3]
        Dev_PT:
          marker_genes: [SLC27A2, CDH6]
        PT:
          marker_genes: [SLC34A1, SLC6A19, SLC22A6, AQP1, SLC3A1, CLDN2, LRP2, CUBN, UGT2B7]
    LOH:
      marker_genes: [SLC12A1, UMOD, CLDN10, POU3F3, IRX1, CLDN16, MAL, CALB1, SLC12A3, GATA3, CDH1]
      subtypes:
        Dev_DT:
          marker_genes: [JAG1, LHX1, CLDN3, ESRRG]
        DT:
          marker_genes: [MAL, SLC14A2, CALB1]
    Proliferative_tubule:
          marker_genes: [UBE2C, MKI67, TOP2A, BIRC5, PCNA, CUBN]
Ureteric_Epithelium:
  marker_genes: [GATA3, SLC26A7, AQP2, RET, WFDC2]
  subtypes:
    Ureteric_Bud:
      marker_genes: [RET]
    Collecting_duct: 
      marker_genes: [AQP2, SLC26A7, GATA3]
      subtypes:
        Collecting_duct_Principal_cells:
          marker_genes: [WFDC2, AQP2]
        Collecting_duct_Intercalated_cells:
          marker_genes: [SLC26A7, SLC4A1, ATP6V1B1]
        Proliferative_collecting_duct_cells:
          marker_genes: [UBE2C, MKI67, TOP2A]
Stromal_cells:
  marker_genes: [COL14A1, COL1A1, COL2A1, PDGFRA, PDGFRB, MEIS1, MEIS2] 
  subtypes:
    Stromal_progenitors:
      marker_genes: [FOXD1, MEIS1, PBX1, NFIB, NFIA, EBF1]
    Proliferative_stroma:
      marker_genes: [UBE2C, DEPDC1B, SCLT1, COL3A1, COL1A1]
    Mesangial_cells:
      marker_genes: [ITGA8, REN, LGALS1]
    Pericytes:                                                           
      marker_genes: [ITGA4, ADGRF5, KCNIP4, PIEZO2, GUCY1A2]  
    Interstitial_Fibroblasts:                                                       
      marker_genes: [COL6A3, COL14A1, COL5A1, COL11A1, COL12A1, C7, COL3A1, COL1A1, DCN, PDGFRA]  
    Activated Fibroblasts:                                                    
      marker_genes: [ACTA2, POSTN, LRP1B, TGFBI]
Endothelial_cells:
  marker_genes: [PECAM1, KDR, CAV1, SOX17]
  subtypes:
    Early_endothelium:
      marker_genes: [EGFL7, NRP2, KDR, GNG11]
    Late_endothelium:
      marker_genes: [PECAM1, CDH5, ESM1, PLVAP]
Off_target_cells:
  marker_genes: [HES6, STMN2, MYOG, FABP7, SRGN, PTPRC, OTX2, CDX2, TUBB3, MYOD1, MYL1] 
  subtypes:
    Neural_progenitor_cells:
      marker_genes: [HES6, STMN2, OTX2, TUBB3]
    Muscle_progenitor_cells:
      marker_genes: [MYOG, MYOD1, TTN, MYL1, PITX2]
    Glial_cells:
      marker_genes: [FABP7, TTYH1, SOX2,FRZB, MSX1]
    Endodermal_cells:
      marker_genes: [CDX2, SI, CDH17, AGR2, APOA1, TTR, FABP1, GSTA1, SHH]  
undifferentiated_pluripotent_cells:
      marker_genes: [L1TD1, POU5F1, USP44]

# All markers in one unique list
# all_markers: []
